// src/components/organisms/LinkEditTable.vue
<template>
  <q-page padding>
    <q-btn
      color="primary"
      label="Create New Link"
      @click="createNewLink"
    ></q-btn>
    <!-- 新規作成ダイアログ -->
    <q-dialog v-model="createDialog">
      <q-card style="width:85%;">
        <q-card-section>
          <div class="text-h6">Create New Link</div>
          <q-form @submit="createLink">
            <q-input v-model="newData.id" label="ID" />
            <q-input v-model="newData.url" label="URL" />
            <!-- 値を取得する -->

            <q-input v-model="newData.ogpUrl" label="OGP URL" />
            <q-input v-model="newData.title" label="Title" />
            <q-input v-model="newData.description" label="Description" />
            <q-btn
              :loading="createLoading"
              label="Create"
              type="submit"
              color="primary"
            />
          </q-form>
          <div v-if="errorMessage" class="text-negative">
            {{ errorMessage }}
          </div>
        </q-card-section>
      </q-card>
    </q-dialog>
    <hr />

    <q-table
      title="Links"
      :rows="links"
      :columns="columns"
      row-key="id"
      :rows-per-page-options="[100]"
      style="width:100%;"
    >
      <template v-slot:body-cell-id="props">
        <q-td :props="props">
          <a :href="props.row.id_link" target="_blank">{{ props.row.id }}</a>
        </q-td>
      </template>

      <template v-slot:body-cell-actions="props">
        <q-td :props="props">
          <q-btn flat color="primary" @click="editLink(props.row)">Edit</q-btn>
          <q-btn flat color="negative" @click="deleteLink(props.row.id)"
            >Delete</q-btn
          >
        </q-td>
      </template>
    </q-table>

    <q-dialog v-model="editDialog">
      <q-card style="width:85%;">
        <q-card-section>
          <div class="text-h6">Edit Link</div>
          <q-form @submit="updateLink">
            <a :href="editData.id_link" target="_blank">{{ editData.id }}</a>
            <q-input v-model="editData.url" label="URL" />
            <q-input v-model="editData.ogpUrl" label="OGP URL" />
            <q-input v-model="editData.title" label="Title" />
            <q-input v-model="editData.description" label="Description" />
            <q-btn label="Update" type="submit" color="primary" />
          </q-form>
        </q-card-section>
      </q-card>
    </q-dialog>
  </q-page>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import {
  collection,
  getFirestore,
  onSnapshot,
  deleteDoc,
  doc,
  updateDoc,
  setDoc
} from 'firebase/firestore';
import { firebaseApp, auth } from 'src/boot/firebase';

const db = getFirestore(firebaseApp);

const links = ref([]);
const editDialog = ref(false);
const createDialog = ref(false);
const editData = ref({});
const newData = ref({});
const createLoading = ref(false);
const errorMessage = ref('');

const columns = [
  {
    name: 'ID',
    required: true,
    label: 'ID',
    align: 'left',
    field: row => row.id,
    sortable: true
  },
  {
    name: 'url',
    required: true,
    label: 'URL',
    align: 'left',
    field: row => row.url,
    sortable: true,
  },
  {
    name: 'ogpUrl',
    label: 'OGP URL',
    align: 'left',
    field: row => row.ogpUrl,
    sortable: true,
  },
  {
    name: 'title',
    label: 'Title',
    align: 'left',
    field: row => row.title,
    sortable: true
  },
  {
    name: 'description',
    label: 'Description',
    align: 'left',
    field: row => row.description,
    sortable: true,

  },
  {
    name: 'title',
    required: true,
    label: 'ID',
    align: 'left',
    field: row => row.id,
    sortable: true
  },
  { name: 'actions', label: 'Actions', align: 'right' }
];

onSnapshot(collection(db, 'Link'), querySnapshot => {
  links.value = querySnapshot.docs.map(doc => ({
    id_link: 'https://yama-code.dev/' + doc.id,
    id: doc.id,
    ...doc.data()
  }));
});

const editLink = link => {
  editData.value = { ...link }; // 編集するリンクのデータをコピー
  editDialog.value = true; // ダイアログを開く
};

const updateLink = async () => {
  if (editData.value.ogpUrl == undefined|| editData.value.title== undefined|| editData.value.description == undefined) {
    await updateDoc(doc(db, 'Link', editData.value.id), {
      url: editData.value.url,
    });
  }else{
    await updateDoc(doc(db, 'Link', editData.value.id), {
      url: editData.value.url,
      ogpUrl: editData.value.ogpUrl,
      title: editData.value.title,
      description: editData.value.description
    });
  }
  editDialog.value = false; // ダイアログを閉じる
};

const deleteLink = async id => {
  await deleteDoc(doc(db, 'Link', id));
};

const createNewLink = () => {
  newData.value = {}; // 新規データの初期化
  createDialog.value = true; // 新規作成ダイアログを開く
};

const createLink = async () => {
  createLoading.value = true;
  errorMessage.value = '';
  try {
    if (newData.value.id && newData.value.url) {
      // ogpUrlとtitleとdescriptionがあるか確認
      if (newData.value.ogpUrl == undefined|| newData.value.title== undefined|| newData.value.description == undefined) {
        await setDoc(doc(db, 'Link', newData.value.id), {
          url: newData.value.url,
        });
      }else{
        await setDoc(doc(db, 'Link', newData.value.id), {
          url: newData.value.url,
          ogpUrl: newData.value.ogpUrl,
          title: newData.value.title,
          description: newData.value.description
        });
      }
      if (newData.value.ogpUrl)
      createDialog.value = false;
    } else {
      throw new Error('ID and URL are required');
    }
  } catch (error) {
    errorMessage.value = error.message;
  } finally {
    createLoading.value = false;
  }
};
</script>

// nextjs-app/src/components/ui/LinkEditTable.tsx
'use client'

import { useState, useEffect } from 'react'
import { collection, onSnapshot, deleteDoc, doc, updateDoc, setDoc } from 'firebase/firestore'
import { db } from '@/lib/firebase'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface LinkData {
  id: string
  url: string
  ogpUrl?: string
  title?: string
  description?: string
  id_link: string
}

export default function LinkEditTable() {
  const [links, setLinks] = useState<LinkData[]>([])
  const [editDialog, setEditDialog] = useState(false)
  const [createDialog, setCreateDialog] = useState(false)
  const [editData, setEditData] = useState<LinkData | null>(null)
  const [newData, setNewData] = useState<Partial<LinkData>>({})
  const [createLoading, setCreateLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  useEffect(() => {
    if (!db) {
      return
    }

    const unsubscribe = onSnapshot(collection(db, 'Link'), (querySnapshot) => {
      const linksData = querySnapshot.docs.map(doc => ({
        id: doc.id,
        id_link: `https://yama-code.dev/${doc.id}`,
        ...doc.data()
      })) as LinkData[]
      setLinks(linksData)
    })

    return () => unsubscribe()
  }, [])

  const editLink = (link: LinkData) => {
    setEditData({ ...link })
    setEditDialog(true)
  }

  const updateLink = async () => {
    if (!editData || !db) return

    try {
      const updatePayload: Partial<LinkData> = { url: editData.url }
      
      if (editData.ogpUrl && editData.title && editData.description) {
        updatePayload.ogpUrl = editData.ogpUrl
        updatePayload.title = editData.title
        updatePayload.description = editData.description
      }

      await updateDoc(doc(db, 'Link', editData.id), updatePayload)
      setEditDialog(false)
    } catch (error) {
      console.error('Error updating link:', error)
    }
  }

  const deleteLink = async (id: string) => {
    if (!db) return

    try {
      await deleteDoc(doc(db, 'Link', id))
    } catch (error) {
      console.error('Error deleting link:', error)
    }
  }

  const createNewLink = () => {
    setNewData({})
    setCreateDialog(true)
  }

  const createLink = async () => {
    if (!newData.id || !newData.url) {
      setErrorMessage('ID and URL are required')
      return
    }

    if (!db) {
      setErrorMessage('Database not available')
      return
    }

    setCreateLoading(true)
    setErrorMessage('')

    try {
      const createPayload: Partial<LinkData> = { url: newData.url }
      
      if (newData.ogpUrl && newData.title && newData.description) {
        createPayload.ogpUrl = newData.ogpUrl
        createPayload.title = newData.title
        createPayload.description = newData.description
      }

      await setDoc(doc(db, 'Link', newData.id), createPayload)
      setCreateDialog(false)
    } catch (error) {
      console.error('Error creating link:', error)
      setErrorMessage('Link creation failed')
    } finally {
      setCreateLoading(false)
    }
  }

  return (
    <div className="space-y-4">
      <Button onClick={createNewLink}>
        Create New Link
      </Button>

      {/* Create Dialog */}
      {createDialog && (
        <Card>
          <CardHeader>
            <CardTitle>Create New Link</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="new-id">ID</Label>
              <Input
                id="new-id"
                value={newData.id || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewData({ ...newData, id: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="new-url">URL</Label>
              <Input
                id="new-url"
                value={newData.url || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewData({ ...newData, url: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="new-ogp-url">OGP URL</Label>
              <Input
                id="new-ogp-url"
                value={newData.ogpUrl || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewData({ ...newData, ogpUrl: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="new-title">Title</Label>
              <Input
                id="new-title"
                value={newData.title || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewData({ ...newData, title: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="new-description">Description</Label>
              <Input
                id="new-description"
                value={newData.description || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewData({ ...newData, description: e.target.value })}
              />
            </div>
            <div className="flex gap-2">
              <Button onClick={createLink} disabled={createLoading}>
                {createLoading ? 'Creating...' : 'Create'}
              </Button>
              <Button variant="outline" onClick={() => setCreateDialog(false)}>
                Cancel
              </Button>
            </div>
            {errorMessage && (
              <p className="text-sm text-destructive">{errorMessage}</p>
            )}
          </CardContent>
        </Card>
      )}

      {/* Edit Dialog */}
      {editDialog && editData && (
        <Card>
          <CardHeader>
            <CardTitle>Edit Link</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>ID</Label>
              <a
                href={editData.id_link}
                target="_blank"
                rel="noopener noreferrer"
                className="block text-blue-600 hover:underline"
              >
                {editData.id}
              </a>
            </div>
            <div>
              <Label htmlFor="edit-url">URL</Label>
              <Input
                id="edit-url"
                value={editData.url || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditData({ ...editData, url: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="edit-ogp-url">OGP URL</Label>
              <Input
                id="edit-ogp-url"
                value={editData.ogpUrl || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditData({ ...editData, ogpUrl: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="edit-title">Title</Label>
              <Input
                id="edit-title"
                value={editData.title || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditData({ ...editData, title: e.target.value })}
              />
            </div>
            <div>
              <Label htmlFor="edit-description">Description</Label>
              <Input
                id="edit-description"
                value={editData.description || ''}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEditData({ ...editData, description: e.target.value })}
              />
            </div>
            <div className="flex gap-2">
              <Button onClick={updateLink}>
                Update
              </Button>
              <Button variant="outline" onClick={() => setEditDialog(false)}>
                Cancel
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Links Table */}
      <Card>
        <CardHeader>
          <CardTitle>Links</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-gray-300">
              <thead>
                <tr className="bg-gray-100">
                  <th className="border border-gray-300 p-2">ID</th>
                  <th className="border border-gray-300 p-2">URL</th>
                  <th className="border border-gray-300 p-2">Title</th>
                  <th className="border border-gray-300 p-2">Actions</th>
                </tr>
              </thead>
              <tbody>
                {links.map((link) => (
                  <tr key={link.id}>
                    <td className="border border-gray-300 p-2">
                      <a
                        href={link.id_link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline"
                      >
                        {link.id}
                      </a>
                    </td>
                    <td className="border border-gray-300 p-2 break-all">
                      {link.url}
                    </td>
                    <td className="border border-gray-300 p-2">
                      {link.title || '-'}
                    </td>
                    <td className="border border-gray-300 p-2">
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          onClick={() => editLink(link)}
                        >
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => deleteLink(link.id)}
                        >
                          Delete
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
